
version: '3'

services:
   app:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    environment:
      APP_PORT: ${PORT}
      
    container_name: app