version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - ${PORT}:${PORT}

    volumes:
      - .:/app

    environment:
      - PORT=${PORT}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
      - SCRAPPER_TIMEOUT=${SCRAPPER_TIMEOUT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
